version: '3'
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017

  mongo_seed:
    image: mongo:latest
    links:
      - mongodb
    volumes:
      - ./mongo-seed:/mongo-seed
    command:
      /mongo-seed/import.sh