version: '3'
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017

  mongo_seed:
    image: mongo:latest
    links:
      - mongodb
    volumes:
      - ./mongo-seed:/mongo-seed
    command:
      /mongo-seed/import.sh
    restart: on-failure
  backend:
    image: dailyreadings
    links:
      - mongodb
    ports:
      - 50001:50001
    restart: on-failure