# Use root/example as user/password credentials
version: "2.1"

services:
  web:
    depends_on:
      - mongodb
    image: vlazar83/dailyreadings-web-app
    ports:
      - 49160:50001
    environment:
      - MONGODB_CONNSTRING=mongodb://root:example@mongodb/dailyReadingsDB?authSource=admin
    restart: always

  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-seed:
    build: ./mongo-seed
    depends_on:
      - mongodb
    links:
      - mongodb

  mongo-express:
    depends_on:
      - mongodb
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017/
